name: Release pipeline

on:
  push:
    tags: [ 'v*.*.*' ]

permissions:
  contents: write  # Required to create GitHub Releases and upload binaries
  packages: write  # Required to push container images to GHCR

jobs:
  release-binaries-and-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Needed by GoReleaser to generate changelogs

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true

      # --- Step A: Compile Binaries & Create GitHub Release ---

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
